version: "3.8"
services:
  anomaly-detection:
    build:
      context: .
    volumes:
      - ./Dataset:/work/Dataset
      - ./notebooks:/work/notebooks
    tty: true
    shm_size: "8gb"
    ports:
      - 8888:8888
    command: "jupyter-lab --allow-root --ip=0.0.0.0 --port=8888 --no-browser --NotebookApp.token='' --notebook-dir=/work"
